import { TerrainMeshSystem } from './TerrainMeshSystem';
import { TerrainModifier } from './TerrainEditorSystem';

export function createTerrainMeshModifier(vts: TerrainMeshSystem): Partial<TerrainModifier> {
  return {
    setVertexElevationsById: (changes) => vts.setVertexElevationsById(changes),
    setVertexPositionsById: (changes) => vts.setVertexPositionsById(changes),
    moveVerticesById: (vertexIds, delta) => vts.moveVerticesById(vertexIds, delta),
    findNearestVertexId: (worldX, worldZ) => vts.findNearestVertexId(worldX, worldZ),
    getVertexPositionById: (vertexId) => vts.getVertexPositionById(vertexId),
    getVertexElevationById: (vertexId) => vts.getVertexElevationById(vertexId) ?? 0,
    getVertexIdsInWorldRadius: (worldX, worldZ, radius) => vts.getVertexIdsInWorldRadius(worldX, worldZ, radius),
    getWorldDimensions: () => vts.getWorldDimensions(),
    rebuildMesh: () => vts.rebuildMesh(),
    paintTerrainType: (faceIds, type) => vts.paintTerrainType(faceIds, type),
    getTopology: () => vts.getTopology(),
    setTopologyMode: (mode) => vts.setTopologyMode(mode),
    getTopologyMode: () => vts.getTopologyMode(),
    setHoveredFace: (faceId) => vts.setHoveredFace(faceId),
    selectFace: (faceId, additive) => vts.selectFace(faceId, additive),
    deselectFace: (faceId) => vts.deselectFace(faceId),
    toggleFaceSelection: (faceId) => vts.toggleFaceSelection(faceId),
    clearSelectedFaces: () => vts.clearSelectedFaces(),
    getSelectedFaceIds: () => vts.getSelectedFaceIds(),
    findFaceAtPosition: (worldX, worldZ) => vts.findFaceAtPosition(worldX, worldZ),
    moveSelectedFaces: (dx, dy, dz) => vts.moveSelectedFaces(dx, dy, dz),
    rotateSelectedVertices: (ax, ay, az) => vts.rotateSelectedVertices(ax, ay, az),
    stampTemplate: (template, cx, cz, scale) => vts.stampTemplate(template, cx, cz, scale),
    findNearestEdgeAt: (x, z) => vts.findNearestEdgeAt(x, z),
    setHoveredEdge: (edgeId) => vts.setHoveredEdge(edgeId),
    selectEdge: (edgeId, additive) => vts.selectEdge(edgeId, additive),
    toggleEdgeSelection: (edgeId) => vts.toggleEdgeSelection(edgeId),
    subdivideSelectedEdge: () => vts.subdivideSelectedEdge(),
    flipSelectedEdge: () => vts.flipSelectedEdge(),
    collapseEdge: (edgeId) => vts.collapseEdge(edgeId),
    getEdgesInBrush: (x, z, r) => vts.getEdgesInBrush(x, z, r),
    setBrushHoveredEdges: (edgeIds) => vts.setBrushHoveredEdges(edgeIds),
    getFacesInBrush: (x, z, r) => vts.getFacesInBrush(x, z, r),
    setBrushHoveredFaces: (faceIds) => vts.setBrushHoveredFaces(faceIds),
    deleteTopologyVertex: (vertexId) => vts.deleteTopologyVertex(vertexId),
    findNearestTopologyVertexAt: (worldX, worldZ) => vts.findNearestTopologyVertexAt(worldX, worldZ),
  };
}
