import { VectorTerrainSystem } from './VectorTerrainSystem';
import { TerrainModifier } from './TerrainEditorSystem';

export function createVectorTerrainModifier(vts: VectorTerrainSystem): Partial<TerrainModifier> {
  return {
    getVertexPosition: (vx, vy) => vts.getVertexPosition(vx, vy),
    setVertexPosition: (vx, vy, pos) => vts.setVertexPosition(vx, vy, pos),
    setVertexPositions: (changes) => vts.setVertexPositions(changes),
    moveVertices: (vertices, delta) => vts.moveVertices(vertices, delta),
    getVertexElevation: (vx, vy) => vts.getVertexElevation(vx, vy),
    setVertexElevation: (vx, vy, z) => vts.setVertexElevation(vx, vy, z),
    setVertexElevations: (changes) => vts.setVertexElevations(changes),
    worldToVertex: (worldX, worldZ) => vts.worldToVertex(worldX, worldZ),
    findNearestVertex: (worldX, worldZ) => vts.findNearestVertex(worldX, worldZ),
    vertexToWorld: (vx, vy) => vts.vertexToWorld(vx, vy),
    getVertexDimensions: () => vts.getVertexDimensions(),
    getWorldDimensions: () => vts.getWorldDimensions(),
    getVertexPositionsGrid: () => vts.getVertexPositionsGrid(),
    getVertexElevationsGrid: () => vts.getVertexElevationsGrid(),
    getLayoutGrid: () => vts.getLayoutGrid(),
    rebuildMesh: () => vts.rebuildMesh(),
    paintTerrainType: (cells, type) => vts.paintTerrainType(cells, type),
    setTopologyMode: (mode) => vts.setTopologyMode(mode),
    getTopologyMode: () => vts.getTopologyMode(),
    setHoveredFace: (faceId) => vts.setHoveredFace(faceId),
    getHoveredFace: () => vts.getHoveredFace(),
    selectFace: (faceId, additive) => vts.selectFace(faceId, additive),
    deselectFace: (faceId) => vts.deselectFace(faceId),
    toggleFaceSelection: (faceId) => vts.toggleFaceSelection(faceId),
    clearSelectedFaces: () => vts.clearFaceSelection(),
    getSelectedFaceIds: () => vts.getSelectedFaceIds(),
    findFaceAtPosition: (worldX, worldZ) => vts.findFaceAtPosition(worldX, worldZ),
    moveSelectedFaces: (dx, dy, dz) => vts.moveSelectedFaces(dx, dy, dz),
    rotateSelectedVertices: (ax, ay, az) => vts.rotateSelectedVertices(ax, ay, az),
    stampTemplate: (template, cx, cz, scale) => vts.stampTemplate(template, cx, cz, scale),
    setFaceTerrain: (faceId, type) => vts.setFaceTerrain(faceId, type),
    getSelectedFaceVertexIds: () => vts.getSelectedFaceVertexIds(),
    getSelectedEdgeVertexIds: () => vts.getSelectedEdgeVertexIds(),
    getSelectedVerticesFromSelection: () => vts.getSelectedVerticesFromSelection(),
    findNearestEdgeAt: (x, z) => vts.findNearestEdgeAt(x, z),
    setHoveredEdge: (edgeId) => vts.setHoveredEdge(edgeId),
    selectEdge: (edgeId, additive) => vts.selectEdge(edgeId, additive),
    toggleEdgeSelection: (edgeId) => vts.toggleEdgeSelection(edgeId),
    deselectAllEdges: () => vts.deselectAllEdges(),
    getSelectedEdgeIds: () => vts.getSelectedEdgeIds(),
    getSelectedEdge: () => vts.getSelectedEdge(),
    subdivideSelectedEdge: () => vts.subdivideSelectedEdge(),
    flipSelectedEdge: () => vts.flipSelectedEdge(),
    collapseEdge: (edgeId) => vts.collapseEdge(edgeId),
    getEdgesInBrush: (x, z, r) => vts.getEdgesInBrush(x, z, r),
    setBrushHoveredEdges: (edgeIds) => vts.setBrushHoveredEdges(edgeIds),
    getFacesInBrush: (x, z, r) => vts.getFacesInBrush(x, z, r),
    setBrushHoveredFaces: (faceIds) => vts.setBrushHoveredFaces(faceIds),
    getVerticesInWorldRadius: (x, z, r) => vts.getVerticesInWorldRadius(x, z, r),
    getVerticesFromEdgesInBrush: (x, z, r) => vts.getVerticesFromEdgesInBrush(x, z, r),
    getVerticesFromFacesInBrush: (x, z, r) => vts.getVerticesFromFacesInBrush(x, z, r),
  };
}
